export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const SIGN_UP='/signup';
export const CHAT_TV ='/chatroom'
export const CHAT_BOX ='/chatbox';
export const GRP_CHAT='/groupchat';
export const NAV ='/navigation'
export const SOLO='/couplechat'
export const PROFILE='/profile'